name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main] # Cambia a 'master' si esa es tu rama principal
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tu repositorio
        uses: actions/checkout@v4
      - name: Instalar, construir y subir tu sitio
        uses: withastro/action@v3
        # with:
          # path: . # Descomenta y ajusta esta línea si tu proyecto Astro está dentro de una subcarpeta

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
